language: node_js

cache:
  directories:
    - "node_modules"

deploy:
  provider: heroku
  api_key:
    secure: "fqS3JcweHGW7tsxSxlrCZJhRaZrsMHs7BaiezP35yoHzL8jekUWKbb+POOh1P2wLa9xaqKiw9aIobte5fC5IsOWqlRqgcAvOed7aUerZTEKcXtrTRZL4UlYLHxABhM3BWHOwsfEnY6UNkn4VdEyruf0rq36dLqkiGRpWOUJQmrSwiKrL3nui0CYHsFDCaqKjl1OWsqFHsjL5jBjCF4wGgUSpbkoNHOOmeCfD4G+2VY31s9F9iYpL6ZwNgeQyVKE+ETQI5nyvDesLg8x5wOoe6upw6rrobhLyrXqdAitS5pwPsBzW41Sk+uFAtK3fbSJoehiaVBURL4mJ1WgmDBDCgZR7QLK2vDMQ7cif8TclZE9Ksu1OWa3Yd1nZpjGbaPTsi39y/LcrgnB5/2Y2tpNwzUtMMWoq8uLfUADmGaMLSAmpE4kfHUwUASgqj9MDLV3uMhU6hnkY4P6lfokOn/UvZUHVqKwrBSa9zPbKrDnp00iv3Ehmax0TjXx8PHtZTN3eXFLHYmKg6npiER2ZQLUGX6GkXpixbodmb/fXrDi4nYaEXn8oHS4tj8rgM0JbyvY/SBfXEw9FswJ6HqqumimRUYPCnZajQekyI251a3l1wnEMXDpElYNrtqNipQgDazIQicjqPdztNbRAFUkMd+zD6UNVwwuIJ035PWWv2JHmDBw="
  on: master
